<a href="https://colab.research.google.com/github/PratviPatel/ML-/blob/main/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello !! ML")

Hello !! ML


# New section

# New section

In [ ]:
print("Hello !!")

Hello !!


In [ ]:
a=20
b=30
c=a+b
print(c)

50


In [ ]:
import numpy as np

In [ ]:
#creation of numpy Array Using List

In [ ]:
a = np.array([1,2,3]) 


In [ ]:
print(a)
print(a.shape)

[1 2 3]
(3,)


In [ ]:
print(a.size)

3


In [ ]:
print(a.shape)

(3,)


In [ ]:
a= np.arange(0,1, 0.2)
print(a)

[0.  0.2 0.4 0.6 0.8]


In [ ]:
A=np.zeros((2,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.random.random((2,3))
print(a)

[[0.64367751 0.94885401 0.79756599]
 [0.58765716 0.07506262 0.03000768]]


In [ ]:
a=np.

In [ ]:
!pip install --upgrade -q gspread

In [ ]:
!pip install --upgrade -q gspread

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

sh = gc.create('A new spreadsheet')

# Open our new sheet and add some data.
worksheet = gc.open('A new spreadsheet').sheet1

cell_list = worksheet.range('A1:C2')

import random
for cell in cell_list:
  cell.value = random.randint(1, 10)

worksheet.update_cells(cell_list)
# Go to https://sheets.google.com to see your new spreadsheet.

ImportError: ignored