In [3]:
import numpy as np
import pandas as pd

In [4]:
data= pd.read_csv("iris.csv")
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
data.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [6]:
data.info

<bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [14]:
# specific print 0 to 2 columns
x=data.iloc[:,0:2]
x

sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [11]:
type(x)

pandas.core.frame.DataFrame

In [15]:
# specific print 2nd number column 
y=data.iloc[:,2]
y

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [18]:
# all columns values
y=data.iloc[:,4].values
y

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [19]:
x.shape

(150, 2)

In [20]:
y.shape

(150,)

In [21]:
from sklearn.preprocessing import LabelEncoder
label_encoder_y= LabelEncoder()
y=label_encoder_y.fit_transform(y)
y

array([ 4,  4,  3,  5,  4,  7,  4,  5,  4,  5,  5,  6,  4,  1,  2,  5,  3,
        4,  7,  5,  7,  5,  0,  7,  8,  6,  6,  5,  4,  6,  6,  5,  5,  4,
        5,  2,  3,  4,  3,  5,  3,  3,  3,  6,  8,  4,  6,  4,  5,  4, 23,
       21, 25, 16, 22, 21, 23, 10, 22, 15, 11, 18, 16, 23, 12, 20, 21, 17,
       21, 15, 24, 16, 25, 23, 19, 20, 24, 26, 21, 11, 14, 13, 15, 27, 21,
       21, 23, 20, 17, 16, 20, 22, 16, 10, 18, 18, 18, 19,  9, 17, 36, 27,
       35, 32, 34, 40, 21, 38, 34, 37, 27, 29, 31, 26, 27, 29, 31, 41, 42,
       26, 33, 25, 41, 25, 33, 36, 24, 25, 32, 34, 37, 39, 32, 27, 32, 37,
       32, 31, 24, 30, 32, 27, 27, 35, 33, 28, 26, 28, 30, 27])

In [22]:
from sklearn.svm import SVC
classifier_svc_sig=SVC (kernel='sigmoid')
classifier_svc_sig

SVC(kernel='sigmoid')

In [39]:
#jetla "()"point size hoy e par thi data no etlo part test side print thase
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)
classifier_svc_sig.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [40]:
#jetlo uper "()" ma size che e testing ma jase nd baki no training maa jase
y_pred=classifier_svc_sig.predict(x_test)
y_pred

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5])

In [41]:
y_test

array([ 5, 32,  4, 18, 24,  4, 18, 31, 35, 23, 34, 26, 20, 24, 32, 12,  7,
        0, 10, 21,  5, 32, 21,  4, 25, 19, 36, 25, 21, 22])

In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
classifier_svc_sig.score(x_test,y_test)

0.06666666666666667